query characterSearch($search: String, $pick: [Int], $omit: [Int]) {
  Page {
    characters(
      search: $search
      id_in: $pick
      id_not_in: $omit
      sort: [SEARCH_MATCH, FAVOURITES_DESC]
    ) {
      id
      age
      gender
      siteUrl
      name {
        userPreferred
      }
      image {
        large
      }
      media(sort: [POPULARITY_DESC, FAVOURITES_DESC]) {
        nodes {
          id
          idMal
          siteUrl
          title {
            userPreferred
          }
        }
      }
    }
  }
}
