query getCharacters($search: String, $pick: [Int]) {
  Page {
    characters(
      search: $search
      id_in: $pick
      sort: [SEARCH_MATCH, FAVOURITES_DESC]
    ) {
      id
      age
      gender
      favourites
      siteUrl
      name {
        userPreferred
      }
      image {
        large
      }
      media(sort: [END_DATE]) {
        nodes {
          id
          idMal
          favourites
          siteUrl
          coverImage {
            large
          }
          title {
            userPreferred
          }
        }
      }
    }
  }
}
